# Generated by Django 6.0.1 on 2026-01-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('DECLARED', 'Declared'), ('VERIFIED', 'Verified'), ('RESTRICTED', 'Restricted')], db_index=True, default='UNVERIFIED', max_length=20)),
                ('declared_name', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('restricted_reason', models.TextField(blank=True, null=True)),
                ('restricted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tokens', models.PositiveSmallIntegerField(default=5)),
                ('locked_tokens', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
