# Generated by Django 6.0.1 on 2026-02-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccess_alter_task_state_task_giver_not_taker_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='giver_not_taker',
        ),
        migrations.AddField(
            model_name='task',
            name='bonus_tokens',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.RemoveField(
            model_name='task',
            name='online',
        ),
    ]
