# Generated by Django 6.0.1 on 2026-02-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tasktype_remove_task_description_remove_task_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='band',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(help_text='What needs to be done (clear description)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.PositiveIntegerField(help_text='Single committed price set by giver'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.tasktype'),
        ),
    ]
