# Generated by Django 6.0.2 on 2026-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
