# Generated by Django 6.0.2 on 2026-04-03 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utr', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('released', 'Released'), ('refunded', 'Refunded'), ('paid_out', 'Paid Out')], default='pending', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_verified', models.BooleanField(default=False)),
                ('reputation_score', models.IntegerField(default=0)),
                ('college_verified', models.BooleanField(default=False)),
                ('college_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_id_image', models.ImageField(blank=True, null=True, upload_to='college_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='declared_at',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='declared_institution',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='declared_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('payment_pending', 'Payment Pending'), ('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='payment_pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state'], name='core_task_state_61f0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['giver'], name='core_task_giver_i_11396b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['taker'], name='core_task_taker_i_4d4762_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='core_task_deadlin_aa9504_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='core_task_created_9e4493_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state', 'deadline'], name='core_task_state_e6a6b1_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.task'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
