# Generated by Django 6.0.2 on 2026-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('pending_verification', 'Pending Verification'), ('released', 'Released'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('paid_out', 'Paid Out')], default='pending', max_length=20),
        ),
    ]
