# Generated by Django 6.0.2 on 2026-06-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
    ]
