# Generated by Django 6.0.2 on 2026-06-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
