# Generated by Django 6.0.2 on 2026-06-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_reviewed_at_task_revision_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=20),
        ),
    ]
