# Generated by Django 6.0.2 on 2026-07-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_task_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
