# Generated by Django 6.0.2 on 2026-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userverification_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('pending_verification', 'Pending Verification'), ('released', 'Released'), ('rejected', 'Rejected'), ('refund_pending', 'Refund Pending'), ('paid_out', 'Paid Out')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('refund_pending', 'Refund Pending')], default='PROCESSING', max_length=20),
        ),
    ]
