# Generated by Django 6.0.2 on 2026-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_payment_status_alter_task_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='earnings_upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earnings_upi_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refund_upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refund_upi_verified',
            field=models.BooleanField(default=False),
        ),
    ]
