# Generated by Django 6.0.2 on 2026-08-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_earnings_upi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('pending_verification', 'Pending Verification'), ('released', 'Released'), ('paid_out', 'Paid Out'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
