# Generated by Django 6.0.2 on 2026-10-03 15:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20260818_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique student registration number (e.g. 12408281)', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[core.models.validate_submission_file_size]),
        ),
    ]
