# Generated by Django 6.0.2 on 2026-10-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fast_tasks_counter',
            field=models.PositiveIntegerField(default=0, help_text='Total same-day completions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speed_streak',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive same-day (<= 24 hr) completions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_completed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed tasks finished as taker'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_posted_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed tasks posted as giver'),
        ),
    ]
