# Generated by Django 6.0.2 on 2026-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_fast_tasks_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaccount',
            name='total_tokens',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
