# Generated by Django 6.0.2 on 2026-10-04 13:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tokenaccount_total_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, help_text='Assignment PDF or instructions file uploaded by giver', null=True, upload_to='task_attachments/', validators=[core.models.validate_submission_file_size]),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, default='', help_text='What needs to be done (clear description)'),
        ),
    ]
